load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = 'Pdp',
    module_name = 'Pdp',
    srcs = glob(['**/*.swift']),
    deps = [],
    visibility = ['//visibility:public'],
)
